"""

  Support Integrity Auditor (SIA) — Inference Script
  Usage: python predict.py --input tickets.csv
         python predict.py --input tickets.csv --output results.csv --dossiers out.json
  Requires: sia_model.pkl (generated by train_pipeline.py)

"""

import re
import json
import pickle
import argparse
import warnings
import numpy as np
import pandas as pd
from scipy.stats import percentileofscore
from sklearn.preprocessing import normalize
from sentence_transformers import SentenceTransformer

warnings.filterwarnings("ignore")


#  KEYWORD LISTS  

CRITICAL_KW = [
    'urgent', 'critical', 'immediately', 'emergency', 'asap',
    'data loss', 'breach', 'fraud', 'outage', 'down', 'broken',
    'escalate', 'legal', 'lawsuit', 'refund', 'charge back',
    'cannot access', 'account locked', 'suspended', 'deleted',
    'not received', 'never arrived', 'still waiting', 'no response',
    'threatening', 'dispute', 'unauthorized', 'blocked', 'corrupted',
    'crash', 'crashed', 'loss of data', 'system failure', 'completely down',
    'business impact', 'revenue loss', 'customers affected', 'production down',
    'cannot process', 'payment down', 'pii exposed', 'legal team',
    'chargeback', 'losing revenue', 'all users', 'account deleted'
]
HIGH_KW = [
    'not working', 'error', 'fail', 'failed', 'issue', 'problem',
    'unable', 'incorrect', 'wrong', 'missing', 'delayed',
    'slow', 'timeout', 'not loading', 'keeps failing', 'broken link',
    'not syncing', 'not saving', 'not sending', 'not receiving',
    'frustrating', 'disappointed', 'unacceptable', 'terrible',
    'not responding', 'keeps crashing', 'data missing', 'access denied'
]
LOW_KW = [
    'how to', 'question', 'information', 'curious', 'wondering',
    'where is', 'hours', 'location', 'update', 'just checking',
    'quick question', 'when you get a chance', 'no rush',
    'at your convenience', 'minor', 'small', 'suggestion', 'feedback',
    'slightly slow', 'seems fine now', 'just wanted to mention',
    'forgot my password', 'reset link worked', 'all good now',
    'display name', 'font size', 'visual suggestion'
]

INV_PRIORITY_MAP = {0: 'Low', 1: 'Medium', 2: 'High', 3: 'Critical'}
PRIORITY_MAP     = {'Low': 0, 'Medium': 1, 'High': 2, 'Critical': 3}


#  UTILITY FUNCTIONS

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    return re.sub(r'\s+', ' ', text).strip()

def nlp_severity_score(text):
    score = 0.0
    for kw in CRITICAL_KW:
        if kw in text: score += 3.0
    for kw in HIGH_KW:
        if kw in text: score += 1.5
    for kw in LOW_KW:
        if kw in text: score -= 2.0
    return float(np.clip(score / 12.0, 0, 1))

def rt_percentile_score(rt_val, reference):
    return percentileofscore(reference, rt_val, kind='rank') / 100.0

def score_to_severity(s, q33, q66, q85):
    if   s >= q85: return 3
    elif s >= q66: return 2
    elif s >= q33: return 1
    else:          return 0

def get_mismatch_type(delta, threshold):
    if delta >= threshold:    return 'Hidden Crisis'
    elif delta <= -threshold: return 'False Alarm'
    return 'Consistent'

def build_dossier(row, proba, W_NLP, W_CLUSTER, W_SAT):
    assert row['mismatch_type'] != 'Consistent', \
        f"build_dossier called on Consistent ticket: {row.get('Ticket_ID','?')}"

    kw_hits = [kw for kw in CRITICAL_KW + HIGH_KW
               if kw in str(row.get('combined_text_clean', ''))]

    rt_val = row.get('Resolution_Time_Hours', 0)
    if rt_val >= 72:
        rt_interp = 'Extremely long resolution time → strong high-severity signal'
    elif rt_val >= 36:
        rt_interp = 'Elevated resolution time → moderate/high severity signal'
    else:
        rt_interp = 'Fast resolution time → low/moderate severity signal'

    cluster_interp = (
        f"Cluster {int(row.get('cluster', -1))} "
        f"(severity score {row.get('cluster_score', 0):.2f}) — "
        + ('high-urgency peer group' if row.get('cluster_score', 0) > 0.5
           else 'low-urgency peer group')
    )

    sat_val = row.get('Satisfaction_Score', 3)
    sat_interp = (
        f"Satisfaction score {int(sat_val)}/5 — "
        + ('low satisfaction may indicate unresolved operational friction'
           if sat_val <= 2
           else 'satisfaction does not strongly indicate unresolved escalation')
    )

    feature_evidence = [
        {'signal': 'keyword',
         'value': ', '.join(kw_hits[:5]) if kw_hits else 'none detected',
         'weight': f'{W_NLP:.0%}', 'source_field': 'Ticket_Description'},
        {'signal': 'resolution_time',
         'value': f"{rt_val} hours",
         'interpretation': rt_interp, 'source_field': 'Resolution_Time_Hours'},
        {'signal': 'semantic_cluster', 'value': cluster_interp,
         'weight': f'{W_CLUSTER:.0%}',
         'source_field': 'Ticket_Subject + Ticket_Description (embedding)'},
        {'signal': 'satisfaction', 'value': sat_interp,
         'weight': f'{W_SAT:.0%}', 'source_field': 'Satisfaction_Score'}
    ]

    delta  = int(row.get('severity_delta', 0))
    assign = str(row.get('Priority_Level', '?'))
    infer  = str(row.get('inferred_severity', '?'))
    mtype  = str(row.get('mismatch_type', '?'))

    strong_kw = ['refund','fraud','crash','down','breach','critical',
                 'emergency','lawsuit','data loss']
    if any(kw in kw_hits for kw in strong_kw):
        lang = 'Strong escalation language detected in the description'
    elif kw_hits:
        lang = 'Moderate urgency indicators detected in the description'
    else:
        lang = 'Behavioral and temporal signals indicate elevated severity'

    if mtype == 'Hidden Crisis':
        analysis = (
            f"Ticket assigned '{assign}' but multi-signal analysis indicates '{infer}' severity "
            f"(delta={delta:+d} levels). {lang} and a resolution time of "
            f"{rt_val}h suggest the issue is more severe than labeled."
        )
    else:
        cluster_reason = ('low-urgency peer patterns' if row.get('cluster_score', 0) < 0.5
                          else 'mixed urgency behavioral patterns')
        rt_phrase = ('fast resolution' if rt_val <= 24
                     else ('moderate resolution duration' if rt_val <= 72
                           else 'extended resolution duration'))
        analysis = (
            f"Ticket assigned '{assign}' but multi-signal analysis indicates '{infer}' severity "
            f"(delta={delta:+d} levels). Routine language, {rt_phrase} "
            f"({rt_val}h), and {cluster_reason} suggest "
            f"the assigned priority may be inflated relative to observed behavioral signals."
        )

    return {
        'ticket_id':           str(row.get('Ticket_ID', '?')),
        'assigned_priority':   assign,
        'inferred_severity':   infer,
        'mismatch_type':       mtype,
        'severity_delta':      delta,
        'feature_evidence':    feature_evidence,
        'constraint_analysis': analysis,
        'confidence':          round(float(proba), 4)
    }


#  LOAD MODEL

def load_model(model_path='sia_model.pkl'):
    print(f"Loading model from {model_path}...")
    with open(model_path, 'rb') as f:
        bundle = pickle.load(f)

    clf                  = bundle['clf']
    pca                  = bundle['pca']
    scaler               = bundle['scaler']
    kmeans               = bundle['kmeans']
    CHANNEL_MAP          = bundle['CHANNEL_MAP']
    CATEGORY_MAP         = bundle['CATEGORY_MAP']
    CLUSTER_SEVERITY_MAP = bundle['CLUSTER_SEVERITY_MAP']
    DEFAULT_CLUSTER_SCORE= bundle['DEFAULT_CLUSTER_SCORE']
    TRAIN_RT_VALUES      = bundle['TRAIN_RT_VALUES']
    Q33, Q66, Q85        = bundle['Q33'], bundle['Q66'], bundle['Q85']
    W_NLP, W_RT          = bundle['W_NLP'], bundle['W_RT']
    W_CLUSTER, W_SAT     = bundle['W_CLUSTER'], bundle['W_SAT']
    MISMATCH_THRESHOLD   = bundle['MISMATCH_THRESHOLD']
    META_COLS            = bundle['META_COLS']
    best_thresh          = bundle['best_thresh']

    print("  Model loaded successfully")
    return (clf, pca, scaler, kmeans, CHANNEL_MAP, CATEGORY_MAP,
            CLUSTER_SEVERITY_MAP, DEFAULT_CLUSTER_SCORE, TRAIN_RT_VALUES,
            Q33, Q66, Q85, W_NLP, W_RT, W_CLUSTER, W_SAT,
            MISMATCH_THRESHOLD, META_COLS, best_thresh)


#  INFERENCE

def predict(csv_path, model_path='sia_model.pkl',
            output_csv='sia_results.csv', output_json='sia_dossiers.json'):

    # Load model bundle
    (clf, pca, scaler, kmeans, CHANNEL_MAP, CATEGORY_MAP,
     CLUSTER_SEVERITY_MAP, DEFAULT_CLUSTER_SCORE, TRAIN_RT_VALUES,
     Q33, Q66, Q85, W_NLP, W_RT, W_CLUSTER, W_SAT,
     MISMATCH_THRESHOLD, META_COLS, best_thresh) = load_model(model_path)

    # Load sentence transformer
    print("  Loading sentence-transformer...")
    st_model = SentenceTransformer('all-MiniLM-L6-v2')

    # ── Load CSV 
    print(f"\nLoading input: {csv_path}")
    df = pd.read_csv(csv_path)
    print(f"  Tickets loaded: {len(df)}")

    required_cols = ['Ticket_Subject', 'Ticket_Description',
                     'Priority_Level', 'Resolution_Time_Hours',
                     'Ticket_Channel', 'Issue_Category']
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        print(f"    Missing columns: {missing} — filling with defaults")
        for c in missing:
            df[c] = 'Unknown' if c != 'Resolution_Time_Hours' else 30

    # Add Ticket_ID if missing
    if 'Ticket_ID' not in df.columns:
        df['Ticket_ID'] = [f'T-{i+1:04d}' for i in range(len(df))]

    # ── Text preprocessing
    df['combined_text'] = (df['Ticket_Subject'].fillna('') + ' ' +
                           df['Ticket_Description'].fillna(''))
    df['combined_text_clean'] = df['combined_text'].apply(clean_text)

    # Priority encoding (null-safe)
    df['priority_num'] = df['Priority_Level'].map(PRIORITY_MAP)
    bad = df['priority_num'].isna().sum()
    if bad > 0:
        print(f"    {bad} unrecognised Priority_Level values — dropping")
        df = df.dropna(subset=['priority_num']).copy()
    df['priority_num'] = df['priority_num'].astype(int)

    df['channel_enc']  = df['Ticket_Channel'].fillna('Unknown').apply(
        lambda x: CHANNEL_MAP.get(x, -1))
    df['category_enc'] = df['Issue_Category'].fillna('Unknown').apply(
        lambda x: CATEGORY_MAP.get(x, -1))

    # ── Signals
    print("  Computing NLP signal...")
    df['nlp_score'] = df['combined_text_clean'].apply(nlp_severity_score)

    print("  Computing RT signal...")
    df['rt_score'] = df['Resolution_Time_Hours'].apply(
        lambda x: rt_percentile_score(x, TRAIN_RT_VALUES))
    df['rt_scaled'] = scaler.transform(df[['Resolution_Time_Hours']]).flatten()

    print("  Generating embeddings...")
    emb = st_model.encode(
        df['combined_text_clean'].tolist(),
        batch_size=64, show_progress_bar=False
    )
    emb = normalize(emb)

    df['cluster'] = kmeans.predict(emb)
    df['cluster_score'] = df['cluster'].apply(
        lambda c: CLUSTER_SEVERITY_MAP.get(int(c), DEFAULT_CLUSTER_SCORE))

    # Satisfaction
    if 'Satisfaction_Score' not in df.columns:
        df['Satisfaction_Score'] = 3
    df['satisfaction_inv'] = 6 - df['Satisfaction_Score'].fillna(3)
    df['sat_score']        = (df['satisfaction_inv'] - 1) / 4.0

    # ── Fusion & severity 
    df['fused_score'] = (
        W_NLP     * df['nlp_score']     +
        W_RT      * df['rt_score']      +
        W_CLUSTER * df['cluster_score'] +
        W_SAT     * df['sat_score']
    )
    df['inferred_severity_num'] = df['fused_score'].apply(
        lambda s: score_to_severity(s, Q33, Q66, Q85))
    df['inferred_severity'] = df['inferred_severity_num'].map(INV_PRIORITY_MAP)
    df['severity_delta']    = df['inferred_severity_num'] - df['priority_num']
    df['mismatch_type']     = df['severity_delta'].apply(
        lambda d: get_mismatch_type(d, MISMATCH_THRESHOLD))

    # ── Extra features 
    df['text_len']          = df['combined_text_clean'].apply(len)
    df['cap_ratio']         = df['combined_text'].apply(
        lambda x: sum(1 for c in str(x) if c.isupper()) / max(len(str(x)), 1))
    df['word_count']        = df['combined_text_clean'].apply(lambda x: len(str(x).split()))
    df['exclamation_count'] = df['combined_text'].apply(lambda x: str(x).count('!'))
    df['crit_kw_count']     = df['combined_text_clean'].apply(
        lambda t: sum(1 for k in CRITICAL_KW if k in t))
    df['low_kw_count']      = df['combined_text_clean'].apply(
        lambda t: sum(1 for k in LOW_KW if k in t))
    df['hi_pri_lo_sat']     = ((df['priority_num'] >= 2) & (df['Satisfaction_Score'] >= 4)).astype(int)
    df['lo_pri_hi_nlp']     = ((df['priority_num'] <= 1) & (df['nlp_score'] >= 0.3)).astype(int)

    # ── Prediction 
    print("  Running inference...")
    X_new = np.hstack([pca.transform(emb), df[META_COLS].values])
    proba = clf.predict_proba(X_new)[:, 1]
    df['pred_label'] = (proba >= best_thresh).astype(int)
    df['pred_proba'] = proba

    # ── Dossier generation 
    flagged  = df[(df['pred_label'] == 1) & (df['mismatch_type'] != 'Consistent')]
    dossiers = [build_dossier(row, row['pred_proba'], W_NLP, W_CLUSTER, W_SAT)
                for _, row in flagged.iterrows()]

    # ── Save outputs 
    out_cols = ['Ticket_ID', 'Priority_Level', 'inferred_severity',
                'severity_delta', 'mismatch_type', 'pred_label', 'pred_proba']
    df[out_cols].to_csv(output_csv, index=False)
    print(f"\n Predictions saved -{output_csv}")

    with open(output_json, 'w') as f:
        json.dump(dossiers, f, indent=2)
    print(f" Dossiers saved   - {output_json}  ({len(dossiers)} flagged tickets)")

    # ── Summary
   
    print("  PREDICTION SUMMARY")
    
    print(f"  Total tickets processed : {len(df)}")
    print(f"  Consistent              : {(df['pred_label']==0).sum()}")
    print(f"  Mismatch flagged        : {(df['pred_label']==1).sum()}")
    print(f"    ├── Hidden Crisis     : {(df['mismatch_type']=='Hidden Crisis').sum()}")
    print(f"    └── False Alarm       : {(df['mismatch_type']=='False Alarm').sum()}")
    print(f"  Decision threshold      : {best_thresh}")
   

    if dossiers:
        print("\n  Sample dossier (first flagged ticket):")
        print(json.dumps(dossiers[0], indent=2))

    return df, dossiers


#  CLI ENTRY POINT

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='SIA — Support Integrity Auditor Inference Script'
    )
    parser.add_argument('--input',    required=True,
                        help='Path to input CSV file with tickets')
    parser.add_argument('--model',    default='sia_model.pkl',
                        help='Path to trained model (default: sia_model.pkl)')
    parser.add_argument('--output',   default='sia_results.csv',
                        help='Output CSV path (default: sia_results.csv)')
    parser.add_argument('--dossiers', default='sia_dossiers.json',
                        help='Output dossiers JSON path (default: sia_dossiers.json)')
    args = parser.parse_args()

    predict(
        csv_path   = args.input,
        model_path = args.model,
        output_csv = args.output,
        output_json= args.dossiers
    )